name : second workflow
on: 
    push:
    workflow_dispatch:

jobs:
    second-workflow:
        runs-on: ubuntu-latest
        steps:
            -   name : second workflow
                run: echo "print second workflow"
            -   name : second workflow func
                run: echo "print workflow func bye"
            -   name: success
                run: exit 0